import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("return-to-original", "routes/return-to-original.tsx"),
  route("account", "routes/account.tsx"),
  route("auth/callback", "routes/auth-callback.ts"),
  route("teams", "routes/teams.tsx"),
  route("team/:teamId", "routes/team.tsx"),
  route("team/:teamId/edit", "routes/edit-team.tsx"),
  route("players", "routes/players.tsx", [
    index("routes/players._index.tsx"),
    route("chemistry", "routes/players.chemistry.tsx"),
    route("chemistry-graph", "routes/players.chemistry-graph.tsx"),
  ]),
  route("player/:playerId", "routes/player.tsx"),
  route("matches", "routes/matches.tsx"),
  route("match/:matchId", "routes/match.tsx"),
  route("drafting", "routes/drafting.tsx"),
  route("stream", "routes/stream.tsx"),
  route("trading", "routes/trading.tsx"),
  route("trade/:tradeId", "routes/trade.tsx"),
  route("trade/with/:teamId", "routes/trade-with.tsx"),
  route("chemistry", "routes/chemistry.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/match-track", "routes/admin-match-track.tsx"),
  route("admin/match/:matchId/stats", "routes/admin-match-stats.tsx"),
  route("kitchen-sink", "routes/kitchen-sink.tsx"),
] satisfies RouteConfig;
